### PR TITLE
remove leftover FactCheck import

### PR DESCRIPTION
**Pull request by Evizero**
addresses #1

### CODE REVIEW

**Comment by Evizero** [comment]
I created this PR in the browser, so to be on the safe side we should see what travis has to say

**Comment by tbreloff** [comment]
Want to remove from REQUIRE while you're at it?

**Comment by Evizero** [comment]
it never was in REQUIRE, which was the initial reason for my issue calling it a "hidden dependency"

**Comment by Evizero** [comment]
oh test/REQUIRE I could remove it from, yes

**Comment by Evizero** [comment]
seems ok to merge

**Comment by tbreloff** [comment]
thanks!

**Pull request merged**
